apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/seerr-team/seerr
  ref:
    branch: develop
  ignore: |
    /*
    !/charts/
