apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: jellyfin
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      tag: latest
    env:
      TZ: Europe/Paris
      JELLYFIN_PublishedServerUrl: "http://192.168.1.21"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      media:
        enabled: true
        existingClaim: jellyfin-media
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    service:
      type: ClusterIP
