apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: latest
            env:
              JELLYFIN_PublishedServerUrl: "http://192.168.1.21"
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 2000m
                memory: 1Gi
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      media:
        existingClaim: jellyfin-media
        globalMounts:
          - path: /media
