apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: envoyproxy
  namespace: envoy-gateway-system
spec:
  interval: 24h
  type: oci
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 1h
  dependsOn:
    - name: envoy-gateway-crds
      namespace: flux-system
  chart:
    spec:
      chart: gateway-helm
      version: "v1.4.1"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
        namespace: envoy-gateway-system
  values:
    deployment:
      replicas: 1
      envoyGateway:
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
    config:
      envoyGateway:
        logging:
          level:
            default: warn
