apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  dependsOn:
    - name: gateway-api-crds
      namespace: flux-system
  interval: 24h
  url: https://charts.gateway.envoyproxy.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  dependsOn:
    - name: gateway-api-crds
      namespace: flux-system
  interval: 1h
  chart:
    spec:
  dependsOn:
    - name: gateway-api-crds
      namespace: flux-system
      chart: gateway-helm
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy-gateway-system
  valuesFrom:
    - kind: ConfigMap
      name: envoy-gateway-values
