# Installation des CRDs Gateway API (prérequis Envoy Gateway)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/kubernetes-sigs/gateway-api/gateway-api-crds
  ref:
    tag: v1.2.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  sourceRef:
    kind: OCIRepository
    name: gateway-api-crds
  wait: true
  timeout: 2m
