apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/seerr-chart
      sourceRef:
        kind: GitRepository
        name: seerr
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: seerr-team/seerr
      tag: ""
    extraEnv:
      - name: JELLYSEERR_URL_BASE
        value: "/jellyseerr"
    podSecurityContext:
      fsGroup: 0
    config:
      persistence:
        existingClaim: jellyseerr-config
    service:
      type: ClusterIP
      port: 5055
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
