apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - helmrelease-sonarr.yaml
  - helmrelease-radarr.yaml
  - helmrelease-prowlarr.yaml
  - helmrelease-transmission.yaml
  - httproute-sonarr.yaml
  - httproute-radarr.yaml
  - httproute-prowlarr.yaml
  - httproute-transmission.yaml
