apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gateway-crds-helm
      version: "v1.4.1"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
        namespace: flux-system
  values:
    crds:
      gatewayAPI:
        enabled: true
        channel: standard
      envoyGateway:
        enabled: true
