apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/raspberry/crds
  wait: true
  timeout: 3m
  force: true
